name: "Test"
on:
  pull_request:
    types: [opened,edited,synchronize,reopened]
  push:
    branches:
      - 'main'
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    if: github.repository_owner == 'trofi'
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
    - run: nix build --extra-experimental-features 'nix-command flakes' -L ".#nix-olde" --show-trace
